### ISSUE TITLE
[TASK] Responsive implementation for DKG Stats

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1814] opened 2023-11-02 03:55 UTC
Currently, the DKG Stats is not responsive on tablet and mobile. 

The design for responsive is ready: 

[Figma link](https://www.figma.com/file/UrIhW5ZikdiIyWWi5XKp9m/%F0%9F%8C%90--DKG-Statistics?type=design&node-id=2321-148756&mode=dev)

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/f7e65fda-89be-43b3-b79b-c273660e3d92)

**Comment by AtelyPham** [comment] 2023-11-02 05:06
Duplicate of https://github.com/webb-tools/webb-dapp/issues/1352.

**Closed by AtelyPham** 2023-11-02 05:06 UTC
Labels: dkg-stats-dapp
