### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by abduloniz1** [webb-tools/webb-dapp#1196] opened 2023-05-11 18:14 UTC
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [✔ ] Chrome
- [✔ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by dutterbutter** [comment] 2023-05-11 18:18
Thanks @abduloniz1 for opening a bug report. Can you provide additional details on the issue. Things that would be helpful:

- Error message 
- Steps to reproduce the issue
- Screenshot / recording of the issue

**Comment by dutterbutter** [comment] 2023-05-15 14:45
Closing due to lack of information.

**Closed by dutterbutter** 2023-05-15 14:45 UTC
Labels: bug 🪲
